In [1]:
# Change the url to iterate the year from 2010 to 2023 and store the URLs in a list
urls = []
for i in range(2010, 2024):
    urls.append('https://www.ncei.noaa.gov/data/global-hourly/access/' + str(i) + '/42809099999.csv')
print(urls)

['https://www.ncei.noaa.gov/data/global-hourly/access/2010/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2011/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2012/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2013/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2014/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2015/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2016/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2017/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2018/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2019/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2020/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2021/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2022/42809099999.csv', 'https://www.ncei.noaa.gov/data/global-hourly/access/2023/42809099999.csv']

In [4]:
# Download the files from the URLs, store them in a list of dataframes, then concatenate
import pandas as pd
dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
df = pd.concat(dfs)
df.head()

C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (17,24,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (17,24,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (17,24,26,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (8,16,17,24,29,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (23,30,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (23,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (22,23,24,31,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (22,23,24,31,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (22,23,27,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (22,23,24,31,32,33,35) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (21,22,23,30,31,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (24,31) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (19,20,25,26,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\3998123113.py:3: DtypeWarning: Columns (23,24,28,32,34) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = [pd.read_csv(url, skiprows=5, header=None) for url in urls]

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,42809099999,2010-01-01T02:20:00,4,22.654739,88.446722,4.87,"NETAJI SUBHASH CHANDRA BOSE INTERNATIONAL, IN",FM-15,VECC,V020,...,"10159,1,99999,9",NaN,"12,1",NaN,NaN,MET080METAR VECC 010220Z 01004KT 1000 R19L/P15...,Q01 003SCCGA1,NaN,NaN,NaN
1,42809099999,2010-01-01T02:50:00,4,22.654739,88.446722,4.87,"NETAJI SUBHASH CHANDRA BOSE INTERNATIONAL, IN",FM-15,VECC,V020,...,"10169,1,99999,9",NaN,"10,1",NaN,NaN,MET087METAR VECC 010250Z 05005KT 1400 R19L/P15...,Q01 003SCCGA1,NaN,NaN,NaN
2,42809099999,2010-01-01T03:00:00,4,22.654739,88.446722,4.87,"NETAJI SUBHASH CHANDRA BOSE INTERNATIONAL, IN",FM-12,VECC,V020,...,NaN,"9,9,999,9,+024,1","05,1",NaN,NaN,SYN070AAXX 01034 42809 31995 03601 10170 2011...,NaN,NaN,NaN,NaN
3,42809099999,2010-01-01T03:50:00,4,22.654739,88.446722,4.87,"NETAJI SUBHASH CHANDRA BOSE INTERNATIONAL, IN",FM-15,VECC,V020,...,"10180,1,99999,9",NaN,"10,1",NaN,NaN,MET057METAR VECC 010350Z 04005KT 2000 BR NSC 1...,Q01 003SCCGA1,NaN,NaN,NaN
4,42809099999,2010-01-01T04:20:00,4,22.654739,88.446722,4.87,"NETAJI SUBHASH CHANDRA BOSE INTERNATIONAL, IN",FM-15,VECC,V020,...,"10180,1,99999,9",NaN,"05,1",NaN,NaN,MET057METAR VECC 010420Z 04006KT 2700 HZ NSC 1...,Q01 003SCCGA1,NaN,NaN,NaN

In [5]:
df.columns

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36],
      dtype='int64')

In [6]:
# Download the files from the URLs to separate dataframes
import pandas as pd
dfs = {url: pd.read_csv(url) for url in urls}

C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (17,24,30,31) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (17,24,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (17,24,26,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (8,16,17,24,29,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (23,30,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (23,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (22,23,24,31,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (22,23,24,31,32,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (22,23,27,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (22,23,24,31,32,33,35) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (21,22,23,30,31,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (24,31) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (19,20,25,26,33) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}
C:\Users\soumy\AppData\Local\Temp\ipykernel_5936\1438329811.py:3: DtypeWarning: Columns (23,24,28,32,34) have mixed types. Specify dtype option on import or set low_memory=False.
  dfs = {url: pd.read_csv(url) for url in urls}

In [7]:
# Merge the dataframes vertically
merged_df = pd.concat([dfs[urls[0]]] + [dfs[url].iloc[1:] for url in urls[1:]])
merged_df.head()
merged_df.to_csv('NETAJI SUBHASH CHANDRA BOSE INTERNATIONAL merged.csv')